# Generated by Django 4.2.11 on 2026-06-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='summary',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('language', 'Languages'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('apps', 'App Development'), ('cloud', 'Cloud'), ('tools', 'Tools'), ('other', 'Other')], max_length=20),
        ),
    ]
