# Generated by Django 4.2.11 on 2026-06-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_personalinfo_summary_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
